"use client";

import type { CgpaResult, SemesterInput } from "./calc";

export interface ReportMeta {
  program: string;
  startSem: number;
  studentName?: string;
  regdNo?: string;
}

/** Build and trigger download of a clean PDF report (client-side). */
export async function downloadReport(
  meta: ReportMeta,
  semesters: SemesterInput[],
  result: CgpaResult
) {
  const { jsPDF } = await import("jspdf");
  const autoTable = (await import("jspdf-autotable")).default;

  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const accent: [number, number, number] = [37, 99, 235];
  const dark: [number, number, number] = [22, 27, 34];
  const muted: [number, number, number] = [107, 114, 128];

  // Header
  doc.setFillColor(...accent);
  doc.rect(0, 0, pageW, 70, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(17);
  doc.text("BPUT CGPA & Percentage Report", 40, 38);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("Generated by BPUT CGPA Calculator", 40, 55);

  // Student info + meta
  doc.setTextColor(...muted);
  doc.setFontSize(10);
  const gen = new Date().toLocaleString();
  let metaY = 98;
  if (meta.studentName) {
    doc.setTextColor(...dark);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text(meta.studentName, 40, metaY);
    doc.setFont("helvetica", "normal");
    metaY += 16;
    if (meta.regdNo) {
      doc.setTextColor(...muted);
      doc.setFontSize(10);
      doc.text(`Regd No: ${meta.regdNo}`, 40, metaY);
      metaY += 14;
    }
    metaY += 4;
  }
  doc.setTextColor(...muted);
  doc.setFontSize(10);
  doc.text(`Program: ${meta.program}`, 40, metaY);
  doc.text(`Generated: ${gen}`, 40, metaY + 14);

  // Summary boxes
  const boxY = metaY + 36;
  const boxW = (pageW - 80 - 16) / 2;
  const drawBox = (x: number, label: string, value: string) => {
    doc.setDrawColor(230, 232, 236);
    doc.setFillColor(250, 251, 252);
    doc.roundedRect(x, boxY, boxW, 70, 6, 6, "FD");
    doc.setTextColor(...accent);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(24);
    doc.text(value, x + boxW / 2, boxY + 36, { align: "center" });
    doc.setTextColor(...muted);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(label, x + boxW / 2, boxY + 56, { align: "center" });
  };
  drawBox(40, "CGPA", result.cgpa.toFixed(2));
  drawBox(40 + boxW + 16, "PERCENTAGE", `${result.percentage.toFixed(2)} %`);

  // Semester table
  const body = semesters.map((s, i) => [
    `Semester ${meta.startSem + i}`,
    s.sgpa.toFixed(2),
    String(s.credits),
    (s.sgpa * s.credits).toFixed(2),
  ]);
  body.push([
    "Total",
    "",
    String(result.totalCredits),
    result.weightedSum.toFixed(2),
  ]);

  autoTable(doc, {
    startY: boxY + 96,
    head: [["Semester", "SGPA", "Credits", "SGPA x Credits"]],
    body,
    theme: "grid",
    styles: { fontSize: 10, cellPadding: 7, textColor: dark },
    headStyles: { fillColor: accent, textColor: 255, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [250, 251, 252] },
    didParseCell: (d: any) => {
      if (d.row.index === body.length - 1) d.cell.styles.fontStyle = "bold";
    },
  });

  const endY = (doc as any).lastAutoTable.finalY + 26;
  doc.setTextColor(...muted);
  doc.setFontSize(9);
  doc.text(
    "CGPA = Sum(SGPA x Credits) / Sum(Credits)     Percentage = (CGPA - 0.5) x 10",
    40,
    endY
  );
  doc.text(
    "This is a provisional, self-calculated report and is not an official BPUT document.",
    40,
    endY + 16
  );

  const slug = meta.studentName
    ? meta.studentName.replace(/\s+/g, "-").replace(/[^a-zA-Z0-9-]/g, "")
    : Date.now().toString();
  doc.save(`BPUT-CGPA-Report-${slug}.pdf`);
}
